basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: contact@krateoplatformops.io
    name: Krateo Support
    url: https://krateo.io
  description: Simple wrapper around GitHub API to provide consisentency of API response
    for Krateo Operator Generator (KOG)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GitHub Plugin API for Krateo Operator Generator (KOG)
  version: "1.0"
paths:
  /repository/{owner}/{repo}/collaborators/{username}/permission:
    get:
      description: Get the permission of a user in a repository
      operationId: get-repo-permission
      parameters:
      - description: Owner of the repository
        in: path
        name: owner
        required: true
        type: string
      - description: Name of the repository
        in: path
        name: repo
        required: true
        type: string
      - description: Username of the collaborator
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get the permission of a user in a repository
  /teamrepository/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}:
    get:
      description: Get the permission of a team in a repository
      operationId: get-team-repo-permission
      parameters:
      - description: Organization of the repository
        in: path
        name: org
        required: true
        type: string
      - description: Slug of the team
        in: path
        name: team_slug
        required: true
        type: string
      - description: Owner of the repository
        in: path
        name: owner
        required: true
        type: string
      - description: Name of the repository
        in: path
        name: repo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get the permission of a team in a repository
schemes:
- http
securityDefinitions:
  Bearer:
    type: basic
swagger: "2.0"
